#!/usr/bin/env python3
"""Draw a delivery-pattern distribution figure for rider personas.

The script reads the persona assignment table generated by
persona_clustering_experiment.py and writes publication-oriented PDF, PNG, and
SVG figures plus a source-data table.
"""

from __future__ import annotations

import argparse
import html
import math
from pathlib import Path

import numpy as np
import pandas as pd


PERSONA_ORDER = [
    "Full-time Workhorse",
    "Lunch-Peak Specialist",
    "Super Stacker",
    "Dinner-Peak Core",
]

PERSONA_SHORT = {
    "Full-time Workhorse": "Full-time",
    "Lunch-Peak Specialist": "Lunch",
    "Super Stacker": "Stacker",
    "Dinner-Peak Core": "Dinner",
}

PERSONA_COLORS = {
    "Full-time Workhorse": "#2F7D5A",
    "Lunch-Peak Specialist": "#C99A2E",
    "Super Stacker": "#D95F02",
    "Dinner-Peak Core": "#4C78A8",
}

TIME_BANDS = [
    ("lunch_ratio", "Lunch", "#DDAA33"),
    ("dinner_ratio", "Dinner", "#5578A6"),
    ("late_night_ratio", "Late night", "#7E6AAD"),
    ("other_ratio", "Other", "#C9D0D6"),
]

METRICS = [
    ("avg_daily_work_duration_hr", "Operating span", "Hours", lambda s: s),
    ("avg_wave_distance_m", "Route distance", "km per wave", lambda s: s / 1000.0),
    ("avg_wave_duration_s", "Route duration", "min per wave", lambda s: s / 60.0),
    ("stacked_order_ratio", "Stacked-order states", "Share of states (%)", lambda s: s * 100.0),
    ("activity_area_km2", "Activity area", "km2", lambda s: s),
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--assignments",
        default="outputs/persona/rider_persona_assignments.csv",
        help="Persona assignment CSV generated by the clustering experiment.",
    )
    parser.add_argument(
        "--output-dir",
        default="outputs/persona",
        help="Directory for the figure and source data.",
    )
    parser.add_argument(
        "--basename",
        default="persona_delivery_pattern_distribution",
        help="Output filename stem.",
    )
    parser.add_argument("--seed", type=int, default=7, help="Jitter seed.")
    return parser.parse_args()


def esc(value: object) -> str:
    return html.escape(str(value), quote=True)


def fmt(value: float) -> str:
    return f"{value:.2f}".rstrip("0").rstrip(".")


def line(x1: float, y1: float, x2: float, y2: float, stroke: str = "#333", width: float = 1.0) -> str:
    return (
        f'<line x1="{x1:.2f}" y1="{y1:.2f}" x2="{x2:.2f}" y2="{y2:.2f}" '
        f'stroke="{stroke}" stroke-width="{width:.2f}"/>'
    )


def rect(
    x: float,
    y: float,
    w: float,
    h: float,
    fill: str,
    stroke: str = "none",
    width: float = 1.0,
    opacity: float | None = None,
    rx: float = 0.0,
) -> str:
    alpha = "" if opacity is None else f' fill-opacity="{opacity:.3f}"'
    return (
        f'<rect x="{x:.2f}" y="{y:.2f}" width="{w:.2f}" height="{h:.2f}" '
        f'rx="{rx:.2f}" fill="{fill}" stroke="{stroke}" stroke-width="{width:.2f}"{alpha}/>'
    )


def circle(
    x: float,
    y: float,
    r: float,
    fill: str,
    stroke: str = "none",
    width: float = 1.0,
    opacity: float | None = None,
) -> str:
    alpha = "" if opacity is None else f' fill-opacity="{opacity:.3f}"'
    return (
        f'<circle cx="{x:.2f}" cy="{y:.2f}" r="{r:.2f}" fill="{fill}" '
        f'stroke="{stroke}" stroke-width="{width:.2f}"{alpha}/>'
    )


def text(
    x: float,
    y: float,
    value: str,
    size: float = 16,
    weight: str = "normal",
    anchor: str = "start",
    fill: str = "#222",
    rotate: float | None = None,
) -> str:
    transform = "" if rotate is None else f' transform="rotate({rotate:.1f} {x:.2f} {y:.2f})"'
    return (
        f'<text x="{x:.2f}" y="{y:.2f}" font-family="Arial" '
        f'font-size="{size:.1f}" font-weight="{weight}" text-anchor="{anchor}" '
        f'fill="{fill}"{transform}>{esc(value)}</text>'
    )


def multiline_text(
    x: float,
    y: float,
    lines: list[str],
    size: float = 15,
    anchor: str = "middle",
    fill: str = "#222",
    line_height: float = 1.15,
) -> list[str]:
    out = [
        (
            f'<text x="{x:.2f}" y="{y:.2f}" font-family="Arial" '
            f'font-size="{size:.1f}" text-anchor="{anchor}" fill="{fill}">'
        )
    ]
    for i, value in enumerate(lines):
        dy = 0 if i == 0 else size * line_height
        out.append(f'<tspan x="{x:.2f}" dy="{dy:.2f}">{esc(value)}</tspan>')
    out.append("</text>")
    return out


def nice_ticks(lo: float, hi: float, n: int = 5) -> list[float]:
    if not np.isfinite(lo) or not np.isfinite(hi) or lo == hi:
        return [lo]
    span = hi - lo
    raw = span / max(n - 1, 1)
    mag = 10 ** math.floor(math.log10(raw))
    steps = np.array([1, 2, 2.5, 5, 10], dtype=float) * mag
    step = float(steps[np.argmin(np.abs(steps - raw))])
    start = math.floor(lo / step) * step
    end = math.ceil(hi / step) * step
    ticks = []
    value = start
    while value <= end + step * 0.5:
        ticks.append(round(value, 10))
        value += step
    return ticks


def scale_linear(value: float, lo: float, hi: float, low_px: float, high_px: float) -> float:
    if hi == lo:
        return (low_px + high_px) / 2
    return low_px + (value - lo) / (hi - lo) * (high_px - low_px)


def panel_header(lines: list[str], x: float, y: float, letter: str, title: str, subtitle: str | None = None) -> None:
    lines.append(text(x, y, letter, size=19, weight="bold", anchor="start"))
    lines.append(text(x + 28, y, title, size=18, weight="bold", anchor="start"))
    if subtitle:
        lines.append(text(x + 28, y + 24, subtitle, size=13.5, anchor="start", fill="#555"))


def draw_time_composition(lines: list[str], df: pd.DataFrame, x: float, y: float, w: float, h: float) -> None:
    panel_header(lines, x, y, "a", "Order-time composition", "Mean share of orders by creation time")
    left = x + 162
    top = y + 58
    bar_w = w - 190
    bar_h = 30
    gap = 42

    for tick in [0, 25, 50, 75, 100]:
        tx = left + tick / 100.0 * bar_w
        lines.append(line(tx, top - 18, tx, top + gap * 4 - 3, stroke="#E5E7EB", width=0.8))
        lines.append(text(tx, top + gap * 4 + 20, str(tick), size=12, anchor="middle", fill="#555"))
    lines.append(text(left + bar_w / 2, top + gap * 4 + 40, "Share of orders (%)", size=13, anchor="middle", fill="#444"))

    grouped = df.groupby("persona", observed=True)[[b[0] for b in TIME_BANDS]].mean().reindex(PERSONA_ORDER)
    for i, persona in enumerate(PERSONA_ORDER):
        cy = top + i * gap
        lines.append(text(x + 8, cy + 20, persona, size=13.2, anchor="start", fill="#222"))
        cursor = left
        for col, label, color in TIME_BANDS:
            share = max(float(grouped.loc[persona, col]), 0.0)
            sw = share * bar_w
            lines.append(rect(cursor, cy, sw, bar_h, color, stroke="white", width=0.8))
            if share >= 0.075:
                lines.append(text(cursor + sw / 2, cy + 20, f"{share * 100:.0f}", size=12, anchor="middle", fill="#222"))
            cursor += sw
        lines.append(rect(left, cy, bar_w, bar_h, "none", stroke="#333", width=0.7))

    legend_x = left
    legend_y = y + h - 76
    cursor = legend_x
    for _, label, color in TIME_BANDS:
        lines.append(rect(cursor, legend_y - 10, 18, 12, color))
        lines.append(text(cursor + 24, legend_y, label, size=12.5, fill="#444"))
        cursor += 108 if label != "Late night" else 132


def draw_distribution_panel(
    lines: list[str],
    df: pd.DataFrame,
    rng: np.random.Generator,
    x: float,
    y: float,
    w: float,
    h: float,
    letter: str,
    title: str,
    y_label: str,
    values_by_persona: dict[str, np.ndarray],
) -> None:
    panel_header(lines, x, y, letter, title)
    plot_x = x + 58
    plot_y = y + 50
    plot_w = w - 82
    plot_h = h - 118
    bottom = plot_y + plot_h

    all_values = np.concatenate([values_by_persona[p] for p in PERSONA_ORDER])
    finite = all_values[np.isfinite(all_values)]
    lo = min(0.0, float(np.nanmin(finite)))
    hi = float(np.nanmax(finite))
    pad = (hi - lo) * 0.08 if hi > lo else 1.0
    hi += pad
    ticks = nice_ticks(lo, hi, n=5)
    lo = min(lo, ticks[0])
    hi = max(hi, ticks[-1])

    def sy(value: float) -> float:
        return scale_linear(value, lo, hi, bottom, plot_y)

    lines.append(line(plot_x, bottom, plot_x + plot_w, bottom, stroke="#333", width=1.0))
    lines.append(line(plot_x, plot_y, plot_x, bottom, stroke="#333", width=1.0))
    for tick in ticks:
        ty = sy(tick)
        lines.append(line(plot_x - 5, ty, plot_x, ty, stroke="#333", width=0.9))
        lines.append(line(plot_x, ty, plot_x + plot_w, ty, stroke="#E6E8EB", width=0.7))
        lines.append(text(plot_x - 10, ty + 4, fmt(tick), size=11.5, anchor="end", fill="#555"))
    lines.append(text(x + 15, plot_y + plot_h / 2, y_label, size=12.5, anchor="middle", fill="#444", rotate=-90))

    x_positions = np.linspace(plot_x + 52, plot_x + plot_w - 32, len(PERSONA_ORDER))
    for persona, xpos in zip(PERSONA_ORDER, x_positions):
        values = values_by_persona[persona]
        color = PERSONA_COLORS[persona]
        jitter = rng.uniform(-24, 24, size=len(values))
        for value, dx in zip(values, jitter):
            lines.append(circle(xpos + dx, sy(float(value)), 2.05, color, opacity=0.28))

        q05, q25, q50, q75, q95 = np.percentile(values, [5, 25, 50, 75, 95])
        mean = float(np.mean(values))
        lines.append(line(xpos, sy(q05), xpos, sy(q95), stroke=color, width=1.5))
        lines.append(line(xpos - 15, sy(q05), xpos + 15, sy(q05), stroke=color, width=1.5))
        lines.append(line(xpos - 15, sy(q95), xpos + 15, sy(q95), stroke=color, width=1.5))
        box_y = min(sy(q25), sy(q75))
        box_h = abs(sy(q25) - sy(q75))
        lines.append(rect(xpos - 24, box_y, 48, max(box_h, 2), color, stroke=color, width=1.2, opacity=0.18, rx=2))
        lines.append(line(xpos - 27, sy(q50), xpos + 27, sy(q50), stroke=color, width=2.3))
        lines.append(circle(xpos, sy(mean), 4.0, "white", stroke=color, width=1.4))
        lines.extend(multiline_text(xpos, bottom + 23, [PERSONA_SHORT[persona]], size=11.5, anchor="middle", fill="#444"))

def build_source_data(df: pd.DataFrame) -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    for persona in PERSONA_ORDER:
        group = df[df["persona"] == persona]
        for col, title, unit, transform in METRICS:
            values = transform(group[col]).dropna().to_numpy(dtype=float)
            rows.append(
                {
                    "panel": title,
                    "metric": col,
                    "unit": unit,
                    "persona": persona,
                    "n": int(len(values)),
                    "mean": float(np.mean(values)),
                    "sd": float(np.std(values, ddof=1)) if len(values) > 1 else 0.0,
                    "min": float(np.min(values)),
                    "p05": float(np.percentile(values, 5)),
                    "p25": float(np.percentile(values, 25)),
                    "median": float(np.percentile(values, 50)),
                    "p75": float(np.percentile(values, 75)),
                    "p95": float(np.percentile(values, 95)),
                    "max": float(np.max(values)),
                }
            )
        for col, label, _ in TIME_BANDS:
            values = group[col].dropna().to_numpy(dtype=float) * 100.0
            rows.append(
                {
                    "panel": "Order-time composition",
                    "metric": col,
                    "unit": "percent",
                    "persona": persona,
                    "n": int(len(values)),
                    "mean": float(np.mean(values)),
                    "sd": float(np.std(values, ddof=1)) if len(values) > 1 else 0.0,
                    "min": float(np.min(values)),
                    "p05": float(np.percentile(values, 5)),
                    "p25": float(np.percentile(values, 25)),
                    "median": float(np.percentile(values, 50)),
                    "p75": float(np.percentile(values, 75)),
                    "p95": float(np.percentile(values, 95)),
                    "max": float(np.max(values)),
                    "time_band": label,
                }
            )
    return pd.DataFrame(rows)


def write_svg(df: pd.DataFrame, path: Path, seed: int) -> None:
    content_width = 1110
    canvas_width = 1180
    height = 1325
    x_offset = (canvas_width - content_width) / 2
    rng = np.random.default_rng(seed)
    df = df.copy()
    df["persona"] = pd.Categorical(df["persona"], categories=PERSONA_ORDER, ordered=True)
    df["other_ratio"] = (1.0 - df[["lunch_ratio", "dinner_ratio", "late_night_ratio"]].sum(axis=1)).clip(lower=0.0)

    lines = [
        (
            f'<svg xmlns="http://www.w3.org/2000/svg" width="{canvas_width}" height="{height}" '
            f'viewBox="0 0 {canvas_width} {height}">'
        ),
        '<rect width="100%" height="100%" fill="white"/>',
        f'<g transform="translate({x_offset:.2f},0)">',
    ]

    panel_w = 510
    panel_h = 376
    xs = [38, 592]
    ys = [48, 448, 848]

    draw_time_composition(lines, df, xs[0], ys[0], panel_w, panel_h)

    metric_specs = [
        ("b", METRICS[0]),
        ("c", METRICS[1]),
        ("d", METRICS[2]),
        ("e", METRICS[3]),
        ("f", METRICS[4]),
    ]
    panel_positions = [(xs[1], ys[0]), (xs[0], ys[1]), (xs[1], ys[1]), (xs[0], ys[2]), (xs[1], ys[2])]
    for (letter, (col, title, unit, transform)), (px, py) in zip(metric_specs, panel_positions):
        values_by_persona = {
            persona: transform(df.loc[df["persona"] == persona, col]).dropna().to_numpy(dtype=float)
            for persona in PERSONA_ORDER
        }
        draw_distribution_panel(lines, df, rng, px, py, panel_w, panel_h, letter, title, unit, values_by_persona)

    legend_x = 38
    legend_y = 1290
    lines.append(text(legend_x, legend_y, "Persona colors:", size=13.5, fill="#555"))
    cursor = legend_x + 108
    for persona in PERSONA_ORDER:
        lines.append(circle(cursor, legend_y - 4, 6, PERSONA_COLORS[persona]))
        label = f"{PERSONA_SHORT[persona]} (n={int((df['persona'] == persona).sum())})"
        lines.append(text(cursor + 13, legend_y + 1, label, size=13, fill="#444"))
        cursor += 240

    lines.append("</g>")
    lines.append("</svg>")
    path.write_text("\n".join(lines), encoding="utf-8")


def write_mpl_figures(df: pd.DataFrame, output_dir: Path, basename: str, seed: int) -> None:
    import matplotlib as mpl
    import matplotlib.pyplot as plt
    from matplotlib.lines import Line2D
    from matplotlib.patches import Patch

    mpl.rcParams.update(
        {
            "font.family": "sans-serif",
            "font.sans-serif": ["Arial", "Helvetica", "DejaVu Sans", "sans-serif"],
            "svg.fonttype": "none",
            "pdf.fonttype": 42,
            "font.size": 6.8,
            "axes.linewidth": 0.55,
            "xtick.major.width": 0.45,
            "ytick.major.width": 0.45,
            "xtick.major.size": 2.0,
            "ytick.major.size": 2.0,
        }
    )

    rng = np.random.default_rng(seed)
    data = df.copy()
    data["persona"] = pd.Categorical(data["persona"], categories=PERSONA_ORDER, ordered=True)
    data["other_ratio"] = (1.0 - data[["lunch_ratio", "dinner_ratio", "late_night_ratio"]].sum(axis=1)).clip(
        lower=0.0
    )

    fig, axes = plt.subplots(2, 3, figsize=(7.15, 4.35), dpi=300)
    fig.subplots_adjust(left=0.062, right=0.992, top=0.958, bottom=0.128, wspace=0.315, hspace=0.485)

    def add_panel_label(ax, letter: str, title: str, subtitle: str | None = None) -> None:
        ax.text(-0.105, 1.075, letter, transform=ax.transAxes, fontsize=7.6, fontweight="bold", va="bottom")
        ax.text(0.000, 1.075, title, transform=ax.transAxes, fontsize=7.2, fontweight="bold", va="bottom")
        if subtitle:
            ax.text(0.000, 1.005, subtitle, transform=ax.transAxes, fontsize=5.6, color="#555555", va="bottom")

    def style_axis(ax) -> None:
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.grid(axis="y", color="#E6E8EB", linewidth=0.45)
        ax.tick_params(labelsize=5.8, pad=1.5)

    ax = axes[0, 0]
    add_panel_label(ax, "a", "Order-time composition", "Mean share of orders by creation time")
    grouped = data.groupby("persona", observed=True)[[b[0] for b in TIME_BANDS]].mean().reindex(PERSONA_ORDER) * 100
    ypos = np.arange(len(PERSONA_ORDER))
    left = np.zeros(len(PERSONA_ORDER))
    for col, label, color in TIME_BANDS:
        values = grouped[col].to_numpy(dtype=float)
        ax.barh(ypos, values, left=left, height=0.56, color=color, edgecolor="white", linewidth=0.45, label=label)
        for yv, start, value in zip(ypos, left, values):
            if value >= 7.5:
                ax.text(start + value / 2, yv, f"{value:.0f}", ha="center", va="center", fontsize=5.4, color="#222222")
        left += values
    ax.set_xlim(0, 100)
    ax.set_yticks(ypos)
    ax.set_yticklabels(PERSONA_SHORT[p] for p in PERSONA_ORDER)
    ax.invert_yaxis()
    ax.set_xlabel("Share of orders (%)", fontsize=5.9, labelpad=1.5)
    ax.grid(axis="x", color="#E6E8EB", linewidth=0.45)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.tick_params(labelsize=5.8, pad=1.5)
    ax.legend(
        loc="lower center",
        bbox_to_anchor=(0.58, -0.315),
        ncol=4,
        frameon=False,
        fontsize=4.95,
        handlelength=1.15,
        handletextpad=0.35,
        columnspacing=0.48,
        borderaxespad=0.0,
    )

    specs = [
        ("b", METRICS[0], axes[0, 1]),
        ("c", METRICS[1], axes[0, 2]),
        ("d", METRICS[2], axes[1, 0]),
        ("e", METRICS[3], axes[1, 1]),
        ("f", METRICS[4], axes[1, 2]),
    ]
    x = np.arange(len(PERSONA_ORDER))
    for letter, (col, title, unit, transform), ax in specs:
        add_panel_label(ax, letter, title)
        values = [
            transform(data.loc[data["persona"] == persona, col]).dropna().to_numpy(dtype=float)
            for persona in PERSONA_ORDER
        ]
        bp = ax.boxplot(
            values,
            positions=x,
            widths=0.42,
            patch_artist=True,
            showfliers=False,
            whis=(5, 95),
            medianprops={"linewidth": 0.75},
            whiskerprops={"linewidth": 0.55},
            capprops={"linewidth": 0.55},
        )
        for patch, persona in zip(bp["boxes"], PERSONA_ORDER):
            patch.set_facecolor(PERSONA_COLORS[persona])
            patch.set_alpha(0.18)
            patch.set_edgecolor(PERSONA_COLORS[persona])
            patch.set_linewidth(0.65)
        for median, persona in zip(bp["medians"], PERSONA_ORDER):
            median.set_color(PERSONA_COLORS[persona])
        for i, (persona, vals) in enumerate(zip(PERSONA_ORDER, values)):
            jitter = rng.uniform(-0.18, 0.18, size=len(vals))
            ax.scatter(
                np.full(len(vals), i) + jitter,
                vals,
                s=2.8,
                color=PERSONA_COLORS[persona],
                alpha=0.22,
                linewidths=0,
                rasterized=True,
            )
            ax.scatter(
                [i],
                [float(np.mean(vals))],
                s=11,
                facecolor="white",
                edgecolor=PERSONA_COLORS[persona],
                linewidth=0.6,
                zorder=4,
            )
        ax.set_xticks(x)
        ax.set_xticklabels([PERSONA_SHORT[p] for p in PERSONA_ORDER], fontsize=5.55)
        ax.set_ylabel(unit, fontsize=5.9, labelpad=2.0)
        style_axis(ax)
        ax.margins(x=0.02)
    handles = [
        Line2D(
            [0],
            [0],
            marker="o",
            linestyle="None",
            color="none",
            markerfacecolor=PERSONA_COLORS[p],
            markeredgewidth=0,
            markersize=4.0,
            label=f"{PERSONA_SHORT[p]} (n={int((data['persona'] == p).sum())})",
        )
        for p in PERSONA_ORDER
    ]
    fig.legend(
        handles=handles,
        loc="lower center",
        ncol=4,
        frameon=False,
        fontsize=5.25,
        handletextpad=0.35,
        columnspacing=0.75,
        bbox_to_anchor=(0.52, 0.018),
        title="Persona colors:",
        title_fontsize=5.25,
    )

    for suffix, kwargs in {
        "pdf": {},
        "svg": {},
        "png": {"dpi": 600},
    }.items():
        fig.savefig(output_dir / f"{basename}.{suffix}", bbox_inches="tight", pad_inches=0.018, **kwargs)
    plt.close(fig)


def main() -> None:
    args = parse_args()
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    assignments = pd.read_csv(args.assignments)
    assignments["persona"] = pd.Categorical(assignments["persona"], categories=PERSONA_ORDER, ordered=True)
    assignments = assignments.sort_values(["persona", "courier_id"])
    assignments["other_ratio"] = (
        1.0 - assignments[["lunch_ratio", "dinner_ratio", "late_night_ratio"]].sum(axis=1)
    ).clip(lower=0.0)

    svg_path = output_dir / f"{args.basename}.svg"
    source_path = output_dir / f"{args.basename}_source_data.csv"
    write_mpl_figures(assignments, output_dir, args.basename, args.seed)
    build_source_data(assignments).to_csv(source_path, index=False)

    print(f"Wrote {output_dir / f'{args.basename}.pdf'}")
    print(f"Wrote {output_dir / f'{args.basename}.png'}")
    print(f"Wrote {svg_path}")
    print(f"Wrote {source_path}")


if __name__ == "__main__":
    main()
